/**
 * The blunder audit [M5-18], its corpus [M5-21], and the committed reference
 * values [M5-31].
 *
 * The audit itself runs here, in the fast suite, because reading recorded
 * values is cheap. The *threshold* on `sharp`'s regret is [M5-19] and lives in
 * `ladder/`, with the rest of the gating lane.
 *
 * The corpus is generated by `arena/generate-corpus.mjs` and committed. It is
 * **stale by design**: a reference regenerated whenever the bot changes
 * measures the bot against itself and calls every regression a tie. So these
 * tests check that the file records what produced it, and that the drift guard
 * actually fires — a corpus and a reference that have quietly parted company
 * would otherwise report a perfect audit.
 */

import { readFileSync } from 'node:fs';
import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';
import { describe, expect, it } from 'vitest';
import { audit, greedy, tier, type AuditCorpus, type Chooser } from '../arena/index.js';

const HERE = dirname(fileURLToPath(import.meta.url));
const CORPUS_FILE = join(HERE, '..', 'arena', 'audit-corpus.json');

const corpus = JSON.parse(readFileSync(CORPUS_FILE, 'utf8')) as AuditCorpus;

/**
 * Small budgets throughout. These tests are about the *audit*, not about how
 * strong a tier is — the threshold on `sharp`'s regret is [M5-19] and runs in
 * `ladder/`, bundled. Running a shipped-budget tier over 34 positions here
 * would spend [B4-60]'s whole 30 seconds several times over.
 */
const AUDIT_NODES = 2000;

describe('the audit corpus [M5-21], [M5-31]', () => {
  it('[M5-21] is recorded, not sampled at run time', () => {
    expect(corpus.positions.length).toBeGreaterThan(10);
    // Every position carries where it came from, so a finding is reproducible.
    for (const entry of corpus.positions) {
      expect(Number.isInteger(entry.seed)).toBe(true);
      expect(Number.isInteger(entry.ply)).toBe(true);
      expect(entry.position.legalActions.length).toBeGreaterThan(0);
    }
  });

  it('[M5-21] holds positions from the last two rounds', () => {
    // Where the intent says blunders matter, and where the boundary horizon of
    // [0004 B4-6] is least forgiving: the position past the boundary it
    // declines to look at may be the last one of the game.
    for (const entry of corpus.positions) {
      expect(entry.roundsFromEnd, `seed ${entry.seed} ply ${entry.ply}`).toBeLessThan(2);
      expect(entry.roundsFromEnd).toBeGreaterThanOrEqual(0);
    }
  });

  it('[M5-31] records the bot commit and the reference budget that produced it', () => {
    // Without these the file is a pile of numbers nobody can date, and
    // "regenerate it deliberately" has nothing to be deliberate about.
    expect(corpus.botCommit).toMatch(/^[0-9a-f]{40}$/);
    expect(corpus.referenceNodes).toBeGreaterThanOrEqual(4_000_000);
  });

  /**
   * [M5-31]'s per-action completeness, and the measurement that made it
   * necessary.
   *
   * Most of the reference's searches do not finish — 261 of 743 complete over
   * this corpus. Without this field the audit cannot tell a terminal *fact*
   * from a *shallower guess*, and one of its populations turned out to be
   * exactly that: at the positions where a move looked like a certain loss, the
   * alternatives valued as still-a-game were simply searched about a ply less
   * deep before the per-move budget ran out.
   */
  it('[M5-31] records whether the reference finished searching each action', () => {
    let complete = 0;
    let total = 0;
    for (const entry of corpus.positions) {
      expect(Object.keys(entry.completed).sort()).toEqual(Object.keys(entry.values).sort());
      for (const action of Object.keys(entry.completed)) {
        expect(typeof entry.completed[Number(action)]).toBe('boolean');
        if (entry.completed[Number(action)]) complete++;
        total++;
      }
    }
    expect(total).toBeGreaterThan(400);
    // Both ends non-empty, or the field is recording nothing useful.
    expect(complete).toBeGreaterThan(0);
    expect(complete).toBeLessThan(total);
  });

  it('[M5-31] scores every legal move of every position', () => {
    for (const entry of corpus.positions) {
      const scored = Object.keys(entry.values).map(Number).sort((a, b) => a - b);
      expect(scored, `seed ${entry.seed} ply ${entry.ply}`).toEqual(
        [...entry.position.legalActions].sort((a, b) => a - b),
      );
    }
  });
});

describe('what the audit reports [M5-18]', () => {
  const report = audit(corpus, tier({ tier: 'sharp', nodes: AUDIT_NODES }));

  it('[M5-18] reports the regret distribution over every position', () => {
    expect(report.positions).toBe(corpus.positions.length);
    expect(report.meanRegret).toBeGreaterThanOrEqual(0);
    expect(report.p95Regret).toBeGreaterThanOrEqual(report.meanRegret);
    expect(report.maxRegret).toBeGreaterThanOrEqual(report.p95Regret);
  });

  it('[M5-18] keeps decisive blunders out of the point average', () => {
    // The corpus samples the last two rounds [M5-21], so many moves end the
    // game and carry `±WIN` [0004 B4-13]. Averaged together, one of those
    // swamps every point-sized mistake — measured, the mean came out near
    // 200 000. Counting them separately is what keeps both numbers readable.
    expect(
      report.scored +
        report.decisiveBlunders.length +
        report.hopeless +
        report.heldOn +
        report.condemned.length,
    ).toBe(report.positions);
    expect(report.scored).toBeGreaterThan(0);
    // The unrankable remainder is split three ways rather than summed. The
    // interesting one is `condemned` — the reference rated the played move a
    // certain loss while not finishing the alternatives — and a single integer
    // buried it among positions where there was nothing to measure at all.
    expect(report.hopeless + report.heldOn + report.condemned.length).toBeGreaterThan(0);
    // Whatever the tier does, the point average stays in point units.
    expect(report.maxRegret).toBeLessThan(1000);
  });

  it('[M5-18] [M5-6] names the worst positions, so a number can be drilled into', () => {
    expect(report.worst.length).toBeGreaterThan(0);
    expect(report.worst.length).toBeLessThanOrEqual(5);
    for (const entry of report.worst) {
      expect(corpus.positions.some((p) => p.seed === entry.seed && p.ply === entry.ply)).toBe(true);
    }
    // Sorted worst-first, or "the worst five" is not what it returns.
    for (let i = 1; i < report.worst.length; i++) {
      expect(report.worst[i - 1].regret).toBeGreaterThanOrEqual(report.worst[i].regret);
    }
  });

  it('[M5-26] never reports a negative regret', () => {
    // The reference searched every legal move, so the played move's value can
    // never exceed the best of them.
    // One cheap chooser is enough: the property is of the arithmetic, not of
    // the player, and the reference searched every legal move — so the played
    // move's value can never exceed the best of them.
    const each = audit(corpus, greedy());
    expect(each.meanRegret).toBeGreaterThanOrEqual(0);
    expect(each.maxRegret).toBeGreaterThanOrEqual(0);
    for (const entry of each.worst) expect(entry.regret).toBeGreaterThanOrEqual(0);
    for (const entry of each.decisiveBlunders) expect(entry.regret).toBeGreaterThan(0);
  });

  /**
   * Compared on **mean point regret**, not on decisive blunders.
   *
   * At the small budget this suite can afford, `sharp` has *more* decisive
   * blunders than `easy` (2 against 1) — which is real, not a bug: a search
   * shallow enough to see a round boundary but not past it mis-times the end of
   * a game in ways a one-ply player never attempts. It goes to 0 by 100 000
   * nodes and stays there at the shipped budget, which is where [M5-19]
   * measures it, in the bundled lane.
   *
   * Point regret separates them at any budget — 1.04 against 1.73 here — and
   * that is enough for what this test is for: showing the instrument can tell
   * two players apart at all.
   */
  it('[M5-18] separates a weak chooser from a strong one', () => {
    const weak = audit(corpus, tier({ tier: 'easy' }));
    const strong = audit(corpus, tier({ tier: 'sharp', nodes: AUDIT_NODES }));
    expect(strong.meanRegret).toBeLessThan(weak.meanRegret);
  }, 30_000);
});

describe('the drift guard [M5-31]', () => {
  /**
   * The failure this exists to prevent: a corpus whose recorded values no
   * longer cover the moves a chooser makes scores every unknown move as zero
   * regret, which reads as a flawless audit.
   *
   * Demonstrated rather than argued — a guard nobody has seen fire is a guard
   * nobody has tested.
   */
  it('[M5-31] throws when the corpus has no value for the move played', () => {
    const chooser: Chooser = (position) => ({
      action: position.legalActions[0],
      nodes: 0,
      curtailed: false,
      depth: 0,
      complete: false,
    });
    const first = corpus.positions[0];
    const played = chooser(first.position).action;
    const holed: AuditCorpus = {
      ...corpus,
      positions: [
        {
          ...first,
          values: Object.fromEntries(
            Object.entries(first.values).filter(([action]) => Number(action) !== played),
          ),
        },
      ],
    };
    expect(() => audit(holed, chooser)).toThrow(/drifted/);
  });

  it('[M5-31] does not throw on the corpus as committed', () => {
    expect(() => audit(corpus, greedy())).not.toThrow();
  });
});
