/**
 * The payload ([0012 T12-7]): the web crate built for the browser, and the
 * shipped milestone's checkpoint and parity file, as one generated module the
 * browser entry point imports. Nothing is fetched at run time ([0003 U3-8]),
 * so the bytes travel inside the bundle, as base64.
 *
 * Refuses unless the shipped milestone's files match the sha256s
 * `web/shipped.json` records ([T12-9]); its `cpuct` and `fpu` come from the
 * config logged with that milestone ([0011 Z11-34]). The output is git-ignored
 * and written only when it changes, so a dev server is not reloaded for
 * nothing.
 */
import { execFileSync } from 'node:child_process';
import { createHash } from 'node:crypto';
import { existsSync, mkdirSync, readFileSync, writeFileSync } from 'node:fs';
import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';

const PACKAGE = join(dirname(fileURLToPath(import.meta.url)), '..');
const WEB = join(PACKAGE, 'web');
const OUT = join(WEB, 'dist', 'payload.ts');

const sha256 = (b) => createHash('sha256').update(b).digest('hex');

/**
 * The shipped milestone's checkpoint, parity file, `cpuct` and `fpu`, or a
 * throw naming what does not match. `shipped` is `web/shipped.json`'s content.
 */
export function shippedMilestone(shipped, packageDir = PACKAGE) {
  const dir = join(packageDir, 'milestones', shipped.run, String(shipped.generation));
  const files = {};
  for (const [name, key] of [['checkpoint.bin', 'checkpointSha256'], ['checkpoint.parity', 'paritySha256']]) {
    const path = join(dir, name);
    if (!existsSync(path)) throw new Error(`shipped.json names ${shipped.run}/${shipped.generation}, which has no ${name}`);
    files[name] = readFileSync(path);
    if (sha256(files[name]) !== shipped[key]) throw new Error(`${path} does not match shipped.json's ${key}`);
  }
  const log = JSON.parse(readFileSync(join(packageDir, 'milestones', 'log.json'), 'utf8'));
  const entry = log.find((e) => e.kind === 'milestone' && e.run === shipped.run && e.generation === shipped.generation);
  if (entry === undefined) throw new Error(`${shipped.run}/${shipped.generation} is not a logged milestone`);
  return { checkpoint: files['checkpoint.bin'], parity: files['checkpoint.parity'], cpuct: entry.config.cpuct, fpu: entry.config.fpu };
}

function main() {
  execFileSync('cargo', ['build', '--locked', '--release', '--quiet', '--lib', '--target', 'wasm32-unknown-unknown'], {
    cwd: WEB,
    stdio: 'inherit',
  });
  const module = readFileSync(join(WEB, 'target', 'wasm32-unknown-unknown', 'release', 'azul_alphazero_web.wasm'));
  const shipped = JSON.parse(readFileSync(join(WEB, 'shipped.json'), 'utf8'));
  const m = shippedMilestone(shipped);
  const text = `// GENERATED by tools/web.mjs ([0012 T12-7]) — do not edit, do not commit.
// The web crate, and milestone ${shipped.run}/${shipped.generation}'s checkpoint and parity file.
export const SHIPPED = ${JSON.stringify(shipped)} as const;
export const CPUCT = ${JSON.stringify(m.cpuct)};
export const FPU = ${JSON.stringify(m.fpu)};
export const MODULE = '${module.toString('base64')}';
export const CHECKPOINT = '${m.checkpoint.toString('base64')}';
export const PARITY = '${m.parity.toString('base64')}';
`;
  mkdirSync(dirname(OUT), { recursive: true });
  if (!existsSync(OUT) || readFileSync(OUT, 'utf8') !== text) writeFileSync(OUT, text);
}

if (process.argv[1] === fileURLToPath(import.meta.url)) main();
