/**
 * Ply-by-ply replay of the recorded oracle games [0002 V2-1].
 *
 * Every vector is fed back through the shuffle seam and compared state for
 * state — not just final score, which two cancelling errors can agree on by
 * accident. The rules under test are the `[E1-n]` cited here; the fixtures are
 * generated by `tools/vectors/dump_vectors.py` and never hand-edited.
 */

import { describe, expect, it } from 'vitest';
import {
  ACTION_SPACE,
  apply,
  clone,
  fromCanonical,
  isLegal,
  legalActions,
  newGame,
  outcome,
  recount,
  tileCensus,
  toCanonical,
  type AzulState,
  type Color,
} from '../src/index.js';
import { deepDiff } from './support/diff.js';
import { FULL_CENSUS, checkCensus, checkInvariants } from './support/invariants.js';
import { gameVectors, loadVectors, type Vector } from './support/vectors.js';

/**
 * The seed every replay is constructed with.
 *
 * Deliberately a constant and deliberately not `generator.pythonSeed`: the
 * recorded seed is provenance, never an input to the replay [0002 V2-2]. With
 * a shuffle injected the seed is unused anyway [0001 E1-61], and passing the
 * oracle's would invite someone to believe the two engines share a bag.
 */
const REPLAY_SEED = 0;

interface Options {
  /** Cross-check `legalActions` against `isLegal` over all 180 [0002 V2-20]. */
  bruteForceLegality?: boolean;
}

interface Replay {
  state: AzulState;
  shuffleCalls: number;
  plies: number;
}

/**
 * Replays one vector, asserting agreement and every per-ply invariant.
 *
 * How a replay *starts* depends on the vector's kind, and the two are not
 * interchangeable [0002 V2-36]. A `game` starts at `newGame`, whose creation
 * shuffle is index 0, so `initial` is **compared** against what `newGame`
 * returns — which is itself the test of [0001 E1-65]. A `position` starts at
 * `fromCanonical`, which does not shuffle [0001 E1-61], so `initial` is
 * loaded and `shuffles[0]` is the first lid recycle after the load.
 */
function replay(v: Vector, options: Options = {}): Replay {
  let shuffleCalls = 0;

  // The seam is a `void` callback that reorders the array it is handed: the
  // harness writes a recorded order into the bag in place, it does not return
  // one [0002 V2-6], [0001 E1-61]. It keeps no cursor — the engine owns the
  // position and passes it as `index`, which is what lets a clone continue the
  // same vector [0001 E1-48].
  const shuffle = (bag: Color[], index: number): void => {
    if (index !== shuffleCalls) {
      throw new Error(`${v.name}: shuffle index ${index}, expected ${shuffleCalls}`);
    }
    if (index >= v.shuffles.length) {
      throw new Error(`${v.name}: shuffle index ${index} past the end of ${v.shuffles.length}`);
    }
    const recorded = v.shuffles[index];
    if (recorded.length !== bag.length) {
      throw new Error(
        `${v.name}: shuffle ${index} holds ${recorded.length} tiles, bag holds ${bag.length}`,
      );
    }
    for (let i = 0; i < recorded.length; i++) bag[i] = recorded[i];
    shuffleCalls++;
  };

  let s: AzulState;
  if (v.kind === 'game') {
    s = newGame(REPLAY_SEED, shuffle);
    const d = deepDiff(toCanonical(s), v.initial);
    if (d !== null) {
      // [E1-65] the opening position, spelled out because none of it is
      // implied by the rules: bag shuffled once, `currentPlayer` 0,
      // `roundIndex` 0, then the first refill.
      expect(toCanonical(s), `${v.name}: newGame opening state [E1-65] — ${d}`).toEqual(v.initial);
    }
  } else {
    s = fromCanonical(v.initial, REPLAY_SEED, shuffle);
    const d = deepDiff(toCanonical(s), v.initial);
    if (d !== null) {
      // [E1-62] `toCanonical(fromCanonical(c, …))` deep-equals `c`.
      expect(toCanonical(s), `${v.name}: fromCanonical round trip [E1-62] — ${d}`).toEqual(
        v.initial,
      );
    }
  }

  // [0002 V2-18] conservation is checked as invariance against the census the
  // replay started with; [0002 V2-35] a fixture holding fewer than 100 tiles
  // must say so, and one that does not say so must hold 100.
  const census = tileCensus(s);
  const short = census.reduce((a, b) => a + b, 0) < 100;
  if (short !== (v.census === 'short')) {
    throw new Error(
      `${v.name}: census ${census.join(',')} but census flag is ${String(v.census)} [V2-35]`,
    );
  }
  const expectedCensus = short ? census : FULL_CENSUS;
  if (!short) expect(census, `${v.name}: initial census [E1-40]`).toEqual(FULL_CENSUS);

  let previousShufflesUsed = s.shufflesUsed;
  for (let i = 0; i < v.plies.length; i++) {
    const ply = v.plies[i];
    const where = `${v.name} ply ${i}`;

    // [0002 V2-7] both engines produce ascending order natively [E1-13], so a
    // legality bug surfaces at the ply that exposes it rather than later.
    const legal = legalActions(s);
    const legalDiff = deepDiff(legal, ply.legal);
    if (legalDiff !== null) {
      expect(legal, `${where}: legalActions [E1-13] — ${legalDiff}`).toEqual(ply.legal);
    }

    if (options.bruteForceLegality === true) {
      // [0002 V2-20] `legalActions` against brute force over all 180 encodings.
      const brute: number[] = [];
      for (let a = 0; a < ACTION_SPACE; a++) if (isLegal(s, a)) brute.push(a);
      const bruteDiff = deepDiff(legal, brute);
      if (bruteDiff !== null) {
        expect(legal, `${where}: legalActions vs isLegal [E1-13] — ${bruteDiff}`).toEqual(brute);
      }
    }

    const before = s.shufflesUsed;
    const roundBefore = s.roundIndex;
    apply(s, ply.action);

    // [E1-47] the generator is consumed only by the shuffles in `newGame` and
    // the lid recycle of [E1-33], so a ply that shuffled is a ply that ran a
    // refill — which is a ply that advanced the round.
    if (s.shufflesUsed !== before && s.roundIndex === roundBefore) {
      throw new Error(`${where}: shuffled without a round transition [E1-47]`);
    }

    const stateDiff = deepDiff(toCanonical(s), ply.state);
    if (stateDiff !== null) {
      expect(toCanonical(s), `${where}: state after apply — ${stateDiff}`).toEqual(ply.state);
    }

    const censusFault = checkCensus(s, expectedCensus);
    if (censusFault !== null) throw new Error(`${where}: ${censusFault}`);
    const fault = checkInvariants(s, shuffleCalls, previousShufflesUsed);
    if (fault !== null) throw new Error(`${where}: ${fault}`);
    previousShufflesUsed = s.shufflesUsed;

    // [0002 V2-21] derived caches are checked fresh: `recount()` on a clone
    // must leave the state unchanged [E1-5].
    const recounted = clone(s);
    recount(recounted);
    const recountDiff = deepDiff(toCanonical(recounted), ply.state);
    if (recountDiff !== null) {
      expect(toCanonical(recounted), `${where}: recount on a clone [E1-5] — ${recountDiff}`).toEqual(
        ply.state,
      );
    }
  }

  // [0002 V2-6] the two closing checks that bound the shuffle count. Neither
  // catches a *skipped* index on its own — that is what comparing
  // `shufflesUsed` at every ply above is for.
  expect(s.shufflesUsed, `${v.name}: shuffles consumed [E1-64]`).toBe(v.shuffles.length);
  expect(shuffleCalls, `${v.name}: shuffle calls served`).toBe(v.shuffles.length);

  expect(s.scores, `${v.name}: final scores`).toEqual(v.final.scores);
  expect(outcome(s), `${v.name}: outcome [E1-39]`).toBe(v.final.outcome);
  expect(s.exhausted, `${v.name}: exhausted [E1-37]`).toBe(v.final.exhausted);
  return { state: s, shuffleCalls, plies: v.plies.length };
}

const vectors = loadVectors();
const games = gameVectors();

describe('conformance vectors', () => {
  it('has at least thirty full games from distinct seeds [V2-13]', () => {
    expect(games.length).toBeGreaterThanOrEqual(30);
    expect(new Set(games.map((g) => g.generator.pythonSeed)).size).toBe(games.length);
  });

  it('steers at least a third of the games away from uniform play [V2-14]', () => {
    // Each generated game records the policy that produced it, so this is the
    // claim itself rather than a proxy for it. Steered play buys unusual
    // *shapes* — heavy floors, contested colours, lopsided walls — not
    // termination; uniform play ends games perfectly well on its own.
    const policies = games.map((g) => g.generator.policy);
    expect(policies.every((p) => typeof p === 'string')).toBe(true);
    const steered = policies.filter((p) => p !== 'uniform');
    expect(steered.length).toBeGreaterThanOrEqual(games.length / 3);
    expect(new Set(policies).size).toBeGreaterThanOrEqual(4);
    expect(new Set(policies)).toContain('uniform');
  });

  it('records every generated vector with its oracle revision [V2-12]', () => {
    const commits = new Set(vectors.map((v) => v.generator.commit));
    expect(commits.size).toBe(1);
  });
});

describe('replay', () => {
  for (const v of vectors) {
    const title =
      v.kind === 'game'
        ? `${v.name} replays ${v.plies.length} plies exactly`
        : `${v.name}: ${v.note ?? ''}`;
    it(title, () => {
      // [0002 V2-20] the brute-force cross-check runs on every ply of one full
      // game per run; it is the same comparison 180 times a ply, so one game
      // buys the coverage and thirty would only buy the runtime.
      replay(v, { bruteForceLegality: v.name === 'game-00.json' });
    });
  }
});

describe('every game vector ends by wall row completion [V2-15]', () => {
  it('never by exhaustion, which a full census cannot reach [E1-36], [E1-37]', () => {
    for (const v of games) {
      expect(v.final.exhausted, `${v.name}`).toBe(false);
      const last = v.plies[v.plies.length - 1].state;
      expect(last.isTerminal, `${v.name}`).toBe(true);
    }
  });

  it('hands the marker back before ending, so a terminal state is lawful [E1-66]', () => {
    for (const v of vectors) {
      const last = v.plies[v.plies.length - 1].state;
      if (!last.isTerminal) continue;
      expect(last.markerInCenter, `${v.name}`).toBe(true);
      expect(last.floorMarker, `${v.name}`).toEqual([false, false]);
    }
  });
});

describe('clone independence [V2-22]', () => {
  it('leaves the parent untouched and replays the rest identically [E1-48]', () => {
    const v = games[1];
    let calls = 0;
    const shuffle = (bag: Color[], index: number): void => {
      const recorded = v.shuffles[index];
      if (recorded === undefined) throw new Error(`shuffle index ${index} past the end`);
      for (let i = 0; i < recorded.length; i++) bag[i] = recorded[i];
      calls++;
    };
    const s = newGame(REPLAY_SEED, shuffle);
    const split = Math.floor(v.plies.length / 2);
    for (let i = 0; i < split; i++) apply(s, v.plies[i].action);

    const parentBefore = toCanonical(s);
    const child = clone(s);

    // Mutation goes through `apply`, never through a field write: a fixture
    // assembled by poking fields tests the poking [0002 V2-3].
    apply(child, v.plies[split].action);
    expect(toCanonical(s), 'the parent is untouched by a move on the clone').toEqual(parentBefore);
    expect(toCanonical(child)).toEqual(v.plies[split].state);

    // The clone continues the parent's stream exactly, injected seam included:
    // the seam is indexed rather than stateful, so nothing is shared that the
    // two states could fight over [E1-61].
    for (let i = split + 1; i < v.plies.length; i++) {
      apply(child, v.plies[i].action);
      expect(toCanonical(child), `clone ply ${i}`).toEqual(v.plies[i].state);
    }
    expect(toCanonical(s), 'the parent is still untouched at the end').toEqual(parentBefore);
    expect(calls).toBe(v.shuffles.length);
  });
});
