//! The parity corpus ([Z11-55]): committed once, compiled in, and never
//! regenerated by accident.

mod support;

use azul_alphazero::parity::{CORPUS_BYTES, CORPUS_COUNT, corpus, generate_corpus, read_corpus};
use azul_alphazero::samples::mask_has;
use azul_alphazero::view::accounts_for;
use support::crate_dir;

/// Writes `train/parity-corpus.bin`. Run once, on purpose:
/// `cargo test --locked --test corpus -- --ignored write_the_corpus`. Every
/// parity file names the corpus's hash, so rewriting it invalidates them all.
#[test]
#[ignore]
fn write_the_corpus() {
    std::fs::write(crate_dir().join("train/parity-corpus.bin"), generate_corpus()).unwrap();
}

/// [Z11-55]: 64 entries in the committed layout, half of them pre-deal views
/// (legal mask all zero), each an input that accounts for its tiles, and the
/// generator still writes exactly the committed bytes — so the corpus every
/// parity file names cannot drift from the code that says what it is.
#[test]
fn the_corpus_is_committed_and_reproducible() {
    let entries = read_corpus(CORPUS_BYTES).expect("the committed corpus parses");
    assert_eq!(entries.len(), CORPUS_COUNT);
    assert_eq!(corpus().len(), CORPUS_COUNT);
    let views = entries.iter().filter(|e| e.legal == [0; 23]).count();
    assert_eq!(views, CORPUS_COUNT / 2, "half are pre-deal views");
    for e in &entries {
        assert!(e.observation.iter().all(|x| x.is_finite()));
        if e.legal != [0; 23] {
            assert!((0..180).any(|a| mask_has(&e.legal, a)));
        }
    }
    assert!(generate_corpus() == CORPUS_BYTES, "the generator no longer writes the committed corpus");
    // Every entry is an input that passes [Z11-51]'s count against 100 tiles.
    let full = azul_engine::AzulState::seeded(1);
    for e in &entries {
        assert!(accounts_for(&e.observation, &full));
    }
}
